const theme = {
  name: 'original',
  colors: {
    canvas: '#008080',
    highlight: '#fff',
    shadow: '#000',
    borderLightest: '#fff',
    borderLighter: '#d3d3d3',
    borderLight: '#808080',
    borderDark: '#222',
    borderDarker: '#000',
    headerBackground: '#000080',
    headerForeground: '#fff',
    material: '#c0c0c0',
    materialDark: '#a0a0a0',
    materialText: '#222',
    materialTextDisabled: '#808080',
    materialTextDisabledShadow: '#fff',
    materialShadow: '#222',
    buttonDefault: '#e0e0e0',
    buttonHover: '#fff',
    buttonActive: '#808080',
    inputBackground: '#fff',
    inputForeground: '#222',
    inputBorder: '#808080',
    inputShadow: '#fff',
    scrollBar: '#c0c0c0',
    tooltip: '#fefbcc',
  },
  fontSizes: {
    normal: '13px',
    large: '16px',
    small: '11px',
  },
  spacing: {
    unit: 4,
    xsmall: 4,
    small: 8,
    medium: 16,
    large: 24,
    xlarge: 32,
  },
  borderWidths: {
    none: 0,
    thin: 1,
    thick: 2,
    extra: 4,
  },
  borderRadius: {
    none: 0,
    soft: 2,
    rounded: 4,
    circle: 999,
  },
  shadows: {
    window: '2px 2px 8px 0 rgba(0,0,0,0.5)',
    input: 'none',
    button: 'none',
  },
  zIndex: {
    modal: 1000,
    menu: 900,
    window: 800,
    taskbar: 700,
    tooltip: 1100,
  },
  fontFamily: [
    'MS Sans Serif',
    'Segoe UI',
    'Arial',
    'Helvetica',
    'sans-serif',
  ].join(','),
};

export default theme;